version: "3"

services:
  ednaff-dot-dev:
    image: ${CONTAINER_IMAGE}
    container_name: ${CONTAINER_NAME}
    expose:
      - 80
    ports:
      - "${VIRTUAL_PORT}:${VIRTUAL_PORT}"
    environment:
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_KEYSIZE: ${LETSENCRYPT_KEYSIZE: 2048}

networks:
  default:
    external:
      name: ${NETWORK}
